export { default as HomePage } from "./HomePage";
export { default as Carousel } from "./Carousel";
export { default as HomePageCard } from "./HomePageCard";
export { default as CarouselCategory } from "./CarouselCategory";
export { default as CarouselProduct } from "./CarouselProduct";
export { default as CarouselProduct2 } from "./CarouselProduct2";
export { default as CarouselProduct3 } from "./CarouselProduct3";
export { default as CarouselProduct4 } from "./CarouselProduct4";
export { default as NavBar } from "./NavBar";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Search } from "./Search";
export { default as Checkout } from "./Checkout";
export { default as ProductPage } from "./ProductPage";
export { default as SearchResults } from "./SearchResults";
export { default as ProductDetails } from "./ProductDetails";
export { default as ProductBadge } from "./ProductBadge";
export { default as ProductRatings } from "./ProductRatings";
  